### PR TITLE
Add mame2003_plus

### PR DESCRIPTION
**Pull request by felinben**
Got that file from libretro-super repo. After install that core should be displayed nicely in the load/update core list. Without it only filename is shown.

### CODE REVIEW

**Comment by RobLoach** [comment]
Is this fixed in the upstream?

**Comment by felinben** [comment]
upstream is fine

(master=) $ date && git log | head -4 && ls dist/info/mame2003_plus_libretro.info
Fri Apr  6 15:36:41 BST 2018
commit bd6148559b25fd70b3a18f962e4ac4094fd8059a
Merge: e61d38e 0f0b6ac
Author: Twinaphex <libretro@gmail.com>
Date:   Fri Apr 6 00:18:09 2018 +0200
dist/info/mame2003_plus_libretro.info

The .txt suffix was added when saving the raw file from github. My bad. Sorry

**Comment by felinben** [comment]
Just a little question: Is the mirroring  libretro-core-info / libretro-super automated or made manually?

**Comment by RobLoach** [comment]
libretro-core-info is just a mirror of the libretro-super .info files. They're done manually periodically. 

If you have `make` and `git` available, you can run...
```
git clone https://github.com/libretro/libretro-core-info.git
cd libretro-core-info
make update
git status
```

This package is used in Flatpak, the Info fiel zip package that's downloaded through RetroArch is handled through libretro-super automatically.

**Comment by felinben** [comment]
Thanks for the clarification Rob.
I compiled RA again and that core is still displayed by its filename (mame2003-plus_libretro.so) instead of the display_name from mame2003-plus_libretro.so (Arcade (MAME 2003-Plus - Experimental)). 
I am better opening an issue ticket at this point but git-bisecting this problem may be problematic. 
Need to figure out how info files are handled when RA compiles.

**Pull request merged**
